name = "BlackBoxOptim"
uuid = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
version = "0.5.0"

[deps]
CPUTime = "a9c8d775-2e2e-55fc-8582-045d282d599e"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpatialIndexing = "d4ead438-fe20-5cc5-a293-4fd39a41b74c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
SpatialIndexing = "≥ 0.1.0"
julia = "≥ 1.0.3"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "Serialization", "SHA", "LinearAlgebra", "Test", "Random", "Printf", "Distributed"]
